## The following requests can be tested using vscode with the "REST client" extension installed.

### HttpTrigger
GET http://localhost:7071/api/HttpTrigger

### GetProject
GET http://localhost:7071/api/GetProject

content-type: application/json
{   
    "ProjectId": "A01"
}


### GetCustomer
GET http://localhost:7071/api/GetCustomers