name: $(Year:yyyy).$(Month).$(DayOfMonth).$(rev:r)
   
trigger:
  - master
  - feature/*
  - bug/*

pool:
    vmImage: windows-latest

variables:
- group: 'test-variable-group'
- name: project_title
  value: 'AzureFunctions.Api'
  
stages:
# - stage: TestVariableGroup
#   displayName: TestVariableGroup
#   jobs:
#   - template: test-variable-group.yml
#     parameters:
#       variableGroup: 'test-variable-group'
#       variableNames: '"$(ServiceUserName)", "$(ServicePassword)"'

- stage: Build
  displayName: Build
  jobs:
  - template: build-dotnet-core-package.yml
    parameters:
      jobTitle: 'Build_Functions_Sites_API'
      project_title: $(project_title)

- stage: Deploy_Dev 
  displayName: Deploy_Dev
  condition: and(succeeded(), or( eq(variables['Build.SourceBranch'], 'refs/heads/master'), contains(variables['Build.SourceBranch'], 'refs/heads/feature') ))
  jobs:  
  - template: deploy-azure.yml
    parameters:
      environment: "GitHubTest"
      targetJson: "GitHubTest.json"
      serviceConnection: "DevOps-AzureDeploymentTemplate"

