parameters:
  #This is used as the pipeline job name. I.e. Build_Pipeline_Azure_Infrastructure_Package
  variableGroup: ''
  #This is the project name. If this is AzureFunctions.Api, the csproj file is expected  to be found in \src\AzureFunctions.Api\AzureFunctions.Api.csproj.
  variableNames: ''

jobs:
- job: ${{ parameters.jobTitle }}
  displayName: 'Print variables and parameters'
  pool:
    vmImage: 'windows-2019'
  condition: succeeded()
  continueOnError: false
  workspace:
    clean: all

  variables:
  - group: ${{ parameters.variableGroup }}

  steps:
  - task: PowerShell@2
    displayName: Show parameters
    inputs:
      targetType: 'inline'
      script: |
          Write-host "ServiceUsername is: $(ServiceUsername)"
          Write-host "ServicePassword is: $(ServicePassword)"
          Write-host "VariableNames is: ${{ parameters.variableNames }}"
          $varName = "ServiceUsername"
          "VarGroupValue: "
          $($varName)

          foreach ($var in ${{ parameters.variableNames }})
          { "Got variable $var"}

          Write-host "System.DefaultWorkingDirectory is: $(System.DefaultWorkingDirectory) Content:"
          ls $(System.DefaultWorkingDirectory)
          Write-host "Build.ArtifactStagingDirectory is: $(Build.ArtifactStagingDirectory) Content:"
          ls $(Build.ArtifactStagingDirectory)
          Write-host "Pipeline.Workspace is: $(Pipeline.Workspace) Content:"
          ls $(Pipeline.Workspace)


